# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180508_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('waterObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WaterObject')),
            ],
        ),
    ]
