# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_metering_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440')),
            ],
        ),
    ]
