# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='metering',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Param'),
            preserve_default=False,
        ),
    ]
