# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-01 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180526_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'},
        ),
        migrations.AlterModelOptions(
            name='metering',
            options={'ordering': ['-id'], 'verbose_name': '\u0418\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u043e\u0432', 'verbose_name_plural': '\u0418\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u043e\u0432'},
        ),
    ]
