# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-29 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180701_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('product_id', models.CharField(max_length=200, verbose_name='ID')),
            ],
        ),
    ]
