# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180820_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438 \u0434\u0430\u043d\u043d\u044b\u0445',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438 \u0434\u0430\u043d\u043d\u044b\u0445',
            },
        ),
        migrations.AlterModelOptions(
            name='metering',
            options={'ordering': ['-time'], 'verbose_name': '\u0418\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u043e\u0432', 'verbose_name_plural': '\u0418\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u043e\u0432'},
        ),
        migrations.AlterField(
            model_name='metering',
            name='time',
            field=models.DateTimeField(max_length=255, verbose_name='Time'),
        ),
        # migrations.AddField(
        #     model_name='metering',
        #     name='dataSource',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DataSource'),
        #     preserve_default=False,
        # ),
    ]
