# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_metering_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('product_id', models.CharField(max_length=200, verbose_name='ID')),
                ('file', models.CharField(max_length=200, verbose_name='\u0424\u0430\u0439\u043b')),
                ('date', models.DateField(max_length=255, verbose_name='Time')),
                ('waterObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WaterObject')),
            ],
        ),
        migrations.AddField(
            model_name='rasterdata',
            name='date',
            field=models.DateField(default='2018-08-11', max_length=255, verbose_name='Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rasterdata',
            name='waterObject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.WaterObject'),
            preserve_default=False,
        ),
    ]
