# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180828_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slug'),
        ),
    ]
