# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_article_slug_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug_name',
        ),
        migrations.AddField(
            model_name='waterobject',
            name='slug_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slug'),
        ),
    ]
