# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-30 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180831_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorLayer',
            fields=[
                ('rasterlayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.RasterLayer')),
            ],
            options={
                'verbose_name': '\u0412\u0435\u043a\u0442\u043e\u0440\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435',
                'verbose_name_plural': '\u0412\u0435\u043a\u0442\u043e\u0440\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435',
            },
            bases=('app.rasterlayer',),
        ),
    ]
