# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_vectorlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterobject',
            name='x1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterobject',
            name='x2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterobject',
            name='y1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterobject',
            name='y2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
