# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-01 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181024_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterlayer',
            name='type',
            field=models.CharField(default='raster', max_length=20, verbose_name='\u0422\u0438\u043f'),
            preserve_default=False,
        ),
    ]
