# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rasterlayer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterlayer',
            name='param',
            field=models.CharField(default='', max_length=20, verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440'),
            preserve_default=False,
        ),
    ]
