# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-07 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rasterlayer_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterlayer',
            name='param',
            field=models.CharField(max_length=512, verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440'),
        ),
        migrations.AlterField(
            model_name='rasterlayer',
            name='type',
            field=models.CharField(max_length=512, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
