# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-26 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20181108_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='metering',
            name='desc',
            field=models.CharField(default='', max_length=255, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metering',
            name='dataSource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataSource', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0434\u0430\u043d\u043d\u044b\u0445'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='time',
            field=models.DateTimeField(max_length=255, verbose_name='\u0412\u0440\u0435\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Param', verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440'),
        ),
        migrations.AlterField(
            model_name='metering',
            name='waterObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WaterObject', verbose_name='\u0412\u043e\u0434\u043d\u044b\u0439 \u043e\u0431\u044a\u0435\u043a\u0442'),
        ),
    ]
