# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-28 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20181126_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='isEcspedit',
            field=models.BooleanField(default=0, verbose_name='\u042d\u043a\u0441\u043f\u0435\u0434\u0438\u0446\u0438\u044f'),
            preserve_default=False,
        ),
    ]
