# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_waterobject_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(max_length=255, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('waterObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WaterObject', verbose_name='\u0412\u043e\u0434\u043d\u044b\u0439 \u043e\u0431\u044a\u0435\u043a\u0442')),
            ],
        ),
    ]
