# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='algorithm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Algorithm', verbose_name='\u0410\u043b\u0433\u043e\u0440\u0438\u0442\u043c'),
            preserve_default=False,
        ),
    ]
