# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190609_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAdmin',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
