# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_task_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RasterData', verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435'),
        ),
    ]
