# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190609_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f'),
        ),
    ]
