# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190609_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u0417\u0430\u0434\u0430\u0447\u0443', 'verbose_name_plural': '\u0417\u0430\u0434\u0430\u0447\u0438'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='time_do',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0434\u043e'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_from',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442'),
        ),
    ]
