# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190609_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'verbose_name': '\u0410\u043b\u0433\u043e\u0440\u0438\u0442\u043c\u044b', 'verbose_name_plural': '\u0410\u043b\u0433\u043e\u0440\u0438\u0442\u043c\u044b'},
        ),
        migrations.AddField(
            model_name='rasterlayer',
            name='pub',
            field=models.CharField(default='n', max_length=5, verbose_name='\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f'),
            preserve_default=False,
        ),
    ]
