# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190610_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('d', '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a'), ('w', '\u0420\u0430\u0431\u043e\u0442\u0430\u0435\u0442'), ('p', '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u0430')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='waterobject',
            name='geojson',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='waterobject',
            name='x1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waterobject',
            name='x2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waterobject',
            name='y1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='waterobject',
            name='y2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
