# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-05 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200405_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterobject',
            name='image',
            field=models.ImageField(default=0, upload_to='waterobj/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
